#!/bin/csh
#
# LSF batch script to run an MPI application
#
#BSUB -P P64000101           # project code
#BSUB -W 00:05                # wall-clock time limit (hrs:mins)
#BSUB -n 4                   # number of MPI tasks in job         
#BSUB -R "span[ptile=16]"    # max MPI tasks per node
#BSUB -J swTest4procs                 # job name
#BSUB -o swTest4procs.%J.out          # output file name in which %J is replaced by the job ID
#BSUB -e swTest4procs.%J.err          # error file name in which %J is replaced by the job ID
#BSUB -q regular             # queue
#BSUB -B
#BSUB -N

limit stacksize unlimited
setenv LD_LIBRARY_PATH ${NETCDF}/lib:$LD_LIBRARY_PATH

mpirun.lsf ./solver_parallel
